# Generated by Django 3.1.2 on 2021-01-21 17:56

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, default='', max_length=50)),
                ('job_title', models.TextField(blank=True, default='', max_length=50)),
                ('url', models.TextField(blank=True, default='')),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('date_applied', models.DateField(default=datetime.date(2021, 1, 21))),
                ('status', models.TextField(blank=True, default='applied', max_length=50)),
            ],
        ),
    ]
