# Generated by Django 3.1.2 on 2021-01-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='status',
            field=models.TextField(blank=True, default='Applied', max_length=50),
        ),
    ]
