# Generated by Django 3.1.2 on 2021-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apps', '0002_auto_20210121_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='contact',
            field=models.TextField(blank=True, default='Hiring Manager'),
        ),
    ]
