# Generated by Django 3.1.2 on 2021-02-12 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apps', '0003_jobapp_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='date_applied',
            field=models.DateField(default=datetime.date(2021, 2, 12)),
        ),
    ]
