# Generated by Django 3.1.2 on 2021-02-13 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_apps', '0007_auto_20210213_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 16, 28, 50, 332604, tzinfo=utc)),
        ),
    ]
