# Generated by Django 3.1.2 on 2021-03-24 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_apps', '0009_auto_20210213_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
