# Generated by Django 3.1.2 on 2020-12-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
