# Generated by Django 3.1.2 on 2020-12-15 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_auto_20201215_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
    ]
