# Generated by Django 3.1.2 on 2020-12-15 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(default=datetime.date(2020, 12, 15), max_length=50)),
                ('name', models.TextField(default='Task Name', max_length=50)),
                ('notes', models.TextField(default='', max_length=500)),
                ('status', models.TextField(default='pending', max_length=50)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_id', to='folder.folder')),
            ],
        ),
    ]
