# Generated by Django 3.1.2 on 2021-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OktaInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('mobilePhone', models.CharField(default='', max_length=100)),
                ('displayName', models.CharField(default='', max_length=100)),
                ('secondEmail', models.CharField(default='', max_length=100)),
                ('login', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
