# Generated by Django 3.1.2 on 2021-02-14 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okta_interview', '0003_auto_20210213_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='oktainterview',
            name='okta_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
    ]
