# Generated by Django 3.1.2 on 2021-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oktainterview',
            name='oktaid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
