# Generated by Django 3.1.2 on 2021-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_oktainterview_oktaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oktainterview',
            name='displayName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='firstName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='lastName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='login',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='mobilePhone',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='oktaid',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oktainterview',
            name='secondEmail',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
