# Generated by Django 3.1.2 on 2021-02-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210219_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
