# Generated by Django 3.1.2 on 2021-02-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20210219_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
