# Generated by Django 3.1.2 on 2021-03-09 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_records',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='member_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='plan_benefit_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
    ]
