# Generated by Django 3.1.2 on 2021-03-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='patients.patient'),
        ),
    ]
